//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextGameProyect.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextGameProyect.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en.
        /// </summary>
        internal static string _in {
            get {
                return ResourceManager.GetString("in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya has usado: [{0}].
        /// </summary>
        internal static string already_used {
            get {
                return ResourceManager.GetString("already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya has cerrado: [{0}]..
        /// </summary>
        internal static string alreadyClosed {
            get {
                return ResourceManager.GetString("alreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya has abierto: [{0}]..
        /// </summary>
        internal static string alreadyOpened {
            get {
                return ResourceManager.GetString("alreadyOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres abrir [{0}]?.
        /// </summary>
        internal static string askToOpen {
            get {
                return ResourceManager.GetString("askToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parece que tienes la llave de [{0}] encima. ¿Quieres usarla?.
        /// </summary>
        internal static string askUseKey {
            get {
                return ResourceManager.GetString("askUseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones disponibles:.
        /// </summary>
        internal static string availableActions {
            get {
                return ResourceManager.GetString("availableActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has cerrado con llave: [{0}]..
        /// </summary>
        internal static string blocked {
            get {
                return ResourceManager.GetString("blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes utilizar esto así..
        /// </summary>
        internal static string cantUseThis {
            get {
                return ResourceManager.GetString("cantUseThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cerrar.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has cerrado: [{0}]..
        /// </summary>
        internal static string closed {
            get {
                return ResourceManager.GetString("closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parece que necesitas una llave para abrir [{0}]..
        /// </summary>
        internal static string closedWithKey {
            get {
                return ResourceManager.GetString("closedWithKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a abajo.
        /// </summary>
        internal static string down {
            get {
                return ResourceManager.GetString("down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tirar.
        /// </summary>
        internal static string drop {
            get {
                return ResourceManager.GetString("drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a este.
        /// </summary>
        internal static string east {
            get {
                return ResourceManager.GetString("east", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string empty {
            get {
                return ResourceManager.GetString("empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Felicidades, has llegado al final!.
        /// </summary>
        internal static string endMessage {
            get {
                return ResourceManager.GetString("endMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a salir.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ir.
        /// </summary>
        internal static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bajar.
        /// </summary>
        internal static string go_down {
            get {
                return ResourceManager.GetString("go down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ir al.
        /// </summary>
        internal static string go_to {
            get {
                return ResourceManager.GetString("go to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a subir.
        /// </summary>
        internal static string go_up {
            get {
                return ResourceManager.GetString("go up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a coger.
        /// </summary>
        internal static string grab {
            get {
                return ResourceManager.GetString("grab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Coger todo?.
        /// </summary>
        internal static string grabAllItems {
            get {
                return ResourceManager.GetString("grabAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Coger [{0}]?.
        /// </summary>
        internal static string grabItem {
            get {
                return ResourceManager.GetString("grabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ayuda.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a inventario.
        /// </summary>
        internal static string inventory {
            get {
                return ResourceManager.GetString("inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has tirado: [{0}]..
        /// </summary>
        internal static string itemDropped {
            get {
                return ResourceManager.GetString("itemDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has cogido: [{0}]..
        /// </summary>
        internal static string itemGrabbed {
            get {
                return ResourceManager.GetString("itemGrabbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes: [{0}]..
        /// </summary>
        internal static string itemNotInInventory {
            get {
                return ResourceManager.GetString("itemNotInInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetos encontrados:.
        /// </summary>
        internal static string itemsFound {
            get {
                return ResourceManager.GetString("itemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetos en tu inventario:.
        /// </summary>
        internal static string itemsInInventory {
            get {
                return ResourceManager.GetString("itemsInInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetos a la vista:.
        /// </summary>
        internal static string itemsInSight {
            get {
                return ResourceManager.GetString("itemsInSight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mirar.
        /// </summary>
        internal static string look {
            get {
                return ResourceManager.GetString("look", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a alrededor.
        /// </summary>
        internal static string lookAround {
            get {
                return ResourceManager.GetString("lookAround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a no.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes tirar: [{0}]..
        /// </summary>
        internal static string noDropThis {
            get {
                return ResourceManager.GetString("noDropThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡No puedes coger eso!.
        /// </summary>
        internal static string noGrab {
            get {
                return ResourceManager.GetString("noGrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡No puedes ir por ahi!.
        /// </summary>
        internal static string noPath {
            get {
                return ResourceManager.GetString("noPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a norte.
        /// </summary>
        internal static string north {
            get {
                return ResourceManager.GetString("north", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a noreste.
        /// </summary>
        internal static string northeast {
            get {
                return ResourceManager.GetString("northeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a noroeste.
        /// </summary>
        internal static string northwest {
            get {
                return ResourceManager.GetString("northwest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas en tu inventario:.
        /// </summary>
        internal static string notesInInventory {
            get {
                return ResourceManager.GetString("notesInInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [{0}] no esta aquí..
        /// </summary>
        internal static string notHere {
            get {
                return ResourceManager.GetString("notHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No te he entendido..
        /// </summary>
        internal static string noUnderstand {
            get {
                return ResourceManager.GetString("noUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes usar [{0}]..
        /// </summary>
        internal static string noUse {
            get {
                return ResourceManager.GetString("noUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes usar [{0}] con [{1}]..
        /// </summary>
        internal static string noUseWith {
            get {
                return ResourceManager.GetString("noUseWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a abrir.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has abierto: [{0}]..
        /// </summary>
        internal static string opened {
            get {
                return ResourceManager.GetString("opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parece que el camino esta bloqueado..
        /// </summary>
        internal static string pathBlocked {
            get {
                return ResourceManager.GetString("pathBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bolsillos.
        /// </summary>
        internal static string pockets {
            get {
                return ResourceManager.GetString("pockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a leer.
        /// </summary>
        internal static string read {
            get {
                return ResourceManager.GetString("read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parece que ha habido un error, no puedo encontrar la habitacion..
        /// </summary>
        internal static string roomNotFound {
            get {
                return ResourceManager.GetString("roomNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sur.
        /// </summary>
        internal static string south {
            get {
                return ResourceManager.GetString("south", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a suroeste.
        /// </summary>
        internal static string southeast {
            get {
                return ResourceManager.GetString("southeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sureste.
        /// </summary>
        internal static string southwest {
            get {
                return ResourceManager.GetString("southwest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has abierto la cerradura de: [{0}]..
        /// </summary>
        internal static string unblocked {
            get {
                return ResourceManager.GetString("unblocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a arriba.
        /// </summary>
        internal static string up {
            get {
                return ResourceManager.GetString("up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usar.
        /// </summary>
        internal static string use {
            get {
                return ResourceManager.GetString("use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a oeste.
        /// </summary>
        internal static string west {
            get {
                return ResourceManager.GetString("west", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a con.
        /// </summary>
        internal static string with {
            get {
                return ResourceManager.GetString("with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a si.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has usado: [{0}].
        /// </summary>
        internal static string you_used {
            get {
                return ResourceManager.GetString("you_used", resourceCulture);
            }
        }
    }
}
