//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextGameProyect.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextGameProyect.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a in.
        /// </summary>
        internal static string _in {
            get {
                return ResourceManager.GetString("in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;ve already used: [{0}].
        /// </summary>
        internal static string already_used {
            get {
                return ResourceManager.GetString("already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;ve already closed: [{0}]..
        /// </summary>
        internal static string alreadyClosed {
            get {
                return ResourceManager.GetString("alreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;ve already opened: [{0}]..
        /// </summary>
        internal static string alreadyOpened {
            get {
                return ResourceManager.GetString("alreadyOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to open [{0}]?.
        /// </summary>
        internal static string askToOpen {
            get {
                return ResourceManager.GetString("askToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It seems like you&apos;ve got the key of  [{0}] in your pocket. Do you want to use it?.
        /// </summary>
        internal static string askUseKey {
            get {
                return ResourceManager.GetString("askUseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available commands:.
        /// </summary>
        internal static string availableActions {
            get {
                return ResourceManager.GetString("availableActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;ve closed with key: [{0}]..
        /// </summary>
        internal static string blocked {
            get {
                return ResourceManager.GetString("blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t use this like that..
        /// </summary>
        internal static string cantUseThis {
            get {
                return ResourceManager.GetString("cantUseThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;ve closed: [{0}]..
        /// </summary>
        internal static string closed {
            get {
                return ResourceManager.GetString("closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It seems like you need a key to open:  [{0}]..
        /// </summary>
        internal static string closedWithKey {
            get {
                return ResourceManager.GetString("closedWithKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a down.
        /// </summary>
        internal static string down {
            get {
                return ResourceManager.GetString("down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a drop.
        /// </summary>
        internal static string drop {
            get {
                return ResourceManager.GetString("drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a east.
        /// </summary>
        internal static string east {
            get {
                return ResourceManager.GetString("east", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string empty {
            get {
                return ResourceManager.GetString("empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Congratulations! You&apos;ve completed the game! I hope you enjoyed it!.
        /// </summary>
        internal static string endgame_text {
            get {
                return ResourceManager.GetString("endgame_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Congrats! You&apos;ve made it until the end!.
        /// </summary>
        internal static string endMessage {
            get {
                return ResourceManager.GetString("endMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a go.
        /// </summary>
        internal static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a go down.
        /// </summary>
        internal static string go_down {
            get {
                return ResourceManager.GetString("go down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a go to.
        /// </summary>
        internal static string go_to {
            get {
                return ResourceManager.GetString("go to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a go up.
        /// </summary>
        internal static string go_up {
            get {
                return ResourceManager.GetString("go up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a grab.
        /// </summary>
        internal static string grab {
            get {
                return ResourceManager.GetString("grab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grab all items?.
        /// </summary>
        internal static string grabAllItems {
            get {
                return ResourceManager.GetString("grabAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grab [{0}]?.
        /// </summary>
        internal static string grabItem {
            get {
                return ResourceManager.GetString("grabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a help.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a inventory.
        /// </summary>
        internal static string inventory {
            get {
                return ResourceManager.GetString("inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;ve dropped: [{0}]..
        /// </summary>
        internal static string itemDropped {
            get {
                return ResourceManager.GetString("itemDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;ve grabbed [{0}]..
        /// </summary>
        internal static string itemGrabbed {
            get {
                return ResourceManager.GetString("itemGrabbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You don&apos;t have: [{0}]..
        /// </summary>
        internal static string itemNotInInventory {
            get {
                return ResourceManager.GetString("itemNotInInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Items found:.
        /// </summary>
        internal static string itemsFound {
            get {
                return ResourceManager.GetString("itemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Items in your inventory:.
        /// </summary>
        internal static string itemsInInventory {
            get {
                return ResourceManager.GetString("itemsInInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Items in sight:.
        /// </summary>
        internal static string itemsInSight {
            get {
                return ResourceManager.GetString("itemsInSight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a look.
        /// </summary>
        internal static string look {
            get {
                return ResourceManager.GetString("look", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a around.
        /// </summary>
        internal static string lookAround {
            get {
                return ResourceManager.GetString("lookAround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a no.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t drop: [{0}]..
        /// </summary>
        internal static string noDropThis {
            get {
                return ResourceManager.GetString("noDropThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t grab this!.
        /// </summary>
        internal static string noGrab {
            get {
                return ResourceManager.GetString("noGrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t go there!.
        /// </summary>
        internal static string noPath {
            get {
                return ResourceManager.GetString("noPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a north.
        /// </summary>
        internal static string north {
            get {
                return ResourceManager.GetString("north", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a northeast.
        /// </summary>
        internal static string northeast {
            get {
                return ResourceManager.GetString("northeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a northwest.
        /// </summary>
        internal static string northwest {
            get {
                return ResourceManager.GetString("northwest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notes in your inventory:.
        /// </summary>
        internal static string notesInInventory {
            get {
                return ResourceManager.GetString("notesInInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [{0}] isn&apos;t here..
        /// </summary>
        internal static string notHere {
            get {
                return ResourceManager.GetString("notHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I didn&apos;t understand you..
        /// </summary>
        internal static string noUnderstand {
            get {
                return ResourceManager.GetString("noUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t use [{0}]..
        /// </summary>
        internal static string noUse {
            get {
                return ResourceManager.GetString("noUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t use [{0}] with [{1}]..
        /// </summary>
        internal static string noUseWith {
            get {
                return ResourceManager.GetString("noUseWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a open.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You opened: [{0}]..
        /// </summary>
        internal static string opened {
            get {
                return ResourceManager.GetString("opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It seems like the path is blocked..
        /// </summary>
        internal static string pathBlocked {
            get {
                return ResourceManager.GetString("pathBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pockets.
        /// </summary>
        internal static string pockets {
            get {
                return ResourceManager.GetString("pockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a read.
        /// </summary>
        internal static string read {
            get {
                return ResourceManager.GetString("read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It seems like I can&apos;t find this room..
        /// </summary>
        internal static string roomNotFound {
            get {
                return ResourceManager.GetString("roomNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a south.
        /// </summary>
        internal static string south {
            get {
                return ResourceManager.GetString("south", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a southeast.
        /// </summary>
        internal static string southeast {
            get {
                return ResourceManager.GetString("southeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a southwest.
        /// </summary>
        internal static string southwest {
            get {
                return ResourceManager.GetString("southwest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You opened the keylock of: [{0}]..
        /// </summary>
        internal static string unblocked {
            get {
                return ResourceManager.GetString("unblocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a up.
        /// </summary>
        internal static string up {
            get {
                return ResourceManager.GetString("up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a use.
        /// </summary>
        internal static string use {
            get {
                return ResourceManager.GetString("use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a west.
        /// </summary>
        internal static string west {
            get {
                return ResourceManager.GetString("west", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a with.
        /// </summary>
        internal static string with {
            get {
                return ResourceManager.GetString("with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You used: [{0}].
        /// </summary>
        internal static string you_used {
            get {
                return ResourceManager.GetString("you_used", resourceCulture);
            }
        }
    }
}
